DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 192
  TEST:
    BATCH_SIZE: 192
  NUM_WORKERS: 8

INPUT:
  SIZE: (448, 448)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "MLC_Policy", "random_flip", "normalize"]
  TRANSFORMS_TEST: ["resize", "normalize"]
  random_resized_crop_scale: (0.6, 1.0)

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5
  LOSSFUNC: "dualcoop"

TEST:
  FINAL_MODEL: "best_val"
  EVALUATOR :  "MLClassification"
  EVALUATOR_ACT : "only_local"

MODEL:
  BACKBONE:
    NAME: "RN101"